### ISSUE TITLE
What are the "transitions"

### ISSUE THREAD

**Issue by fgregg** [dirko/hacrf_sparse_cpp#2]
What are the "transitions." It seems like they have something to do with the dynamic programming, but I can't quite make sense of them?

https://github.com/dirko/hacrf_sparse_cpp/blob/master/crf_ed.cpp#L334-335

**Comment by dirko** [comment]
Hi! Hope you are doing well.

A transition is a pair (see https://github.com/dirko/hacrf_sparse_cpp/blob/master/crf_ed.cpp#L267) that represents either a 'match/substitution', 'insertion', or 'deletion'. For example the transition (-1, -1) represents a match or substitution. When the delta (-1, -1) is added to a lattice coordinate, we move one up and one left in the lattice.

So you're right about the dynamic programming - we fill the two-dimensional tables (which represents a lattice) by visiting each cell in the table and filling it with values obtained by using values in neighbouring cells. We decide which neighbouring cells to visit by enumerating all the 'transitions' and adding these coordinate pairs to the current cell's coordinates.
